name: CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv lock
          uv sync
          # Ensure dev tools also installed inside the uv environment
          uv add pytest
          uv run python -c "import numpy, pandas, sklearn, xgboost, mlflow; print('deps ok')"
          

      - name: Run tests
        run: |
          uv run python -m pytest -q


